/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SendRouteImport } from './routes/send'
import { Route as UnitsIndexRouteImport } from './routes/units.index'
import { Route as UnitsUnitIdRouteImport } from './routes/units.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsUnitIdRoute = UnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/reports': typeof ReportsRoute
  '/send': typeof SendRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/units/': typeof UnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/reports': typeof ReportsRoute
  '/send': typeof SendRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/units': typeof UnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/reports': typeof ReportsRoute
  '/send': typeof SendRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/units/': typeof UnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/login'
    | '/receive'
    | '/reports'
    | '/send'
    | '/units/$unitId'
    | '/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/login'
    | '/receive'
    | '/reports'
    | '/send'
    | '/units/$unitId'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/login'
    | '/receive'
    | '/reports'
    | '/send'
    | '/units/$unitId'
    | '/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  ReceiveRoute: typeof ReceiveRoute
  ReportsRoute: typeof ReportsRoute
  SendRoute: typeof SendRoute
  UnitsUnitIdRoute: typeof UnitsUnitIdRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$unitId': {
      id: '/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof UnitsUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  ReceiveRoute: ReceiveRoute,
  ReportsRoute: ReportsRoute,
  SendRoute: SendRoute,
  UnitsUnitIdRoute: UnitsUnitIdRoute,
  UnitsIndexRoute: UnitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
